[package]
name = "blind-71"
version = "0.1.0"
authors = ["plumenator"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
